### ISSUE TITLE
Erroring out after entering song number

### ISSUE THREAD

**Issue by nathantym** [bjarneo/Spotipy#11]
```
Type song number and press <enter> to play. Press <enter> for new search.
> 2
22:32: syntax error: A identifier can’t go after this identifier. (-2740)
```

After doing a quick google, it looks like it has to do with osascript.

**Comment by bjarneo** [comment]
Did you start spotify before running this cli remote?

**Comment by nathantym** [comment]
I thought I did, but I guess the iTunes version of Spotify is different from the desktop application, so that solves that problem. I'm interested in writing something that checks if there is a process running for Spotify and if there isn't it opens it, which will fix the errors surrounding Spotify not being open.

**Comment by nathantym** [comment]
I added a function to the DarwinSpotipy class to check if Spotify is running and if it's not, it opens it. I need to test this and add in the functionality for it to possibly occur upon start of the cli script. Also it's probably a good idea to check if it's installed before it tries to open Spotify for extra error handling.

**Comment by bjarneo** [comment]
Thanks for your contribution :)
