### ISSUE TITLE
Check Pytify on OSX

### ISSUE THREAD

**Issue by bjarneo** [bjarneo/Spotipy#16]
As the title says. Just to be sure.

**Comment by snipem** [comment]
![bildschirmfoto 2015-04-12 um 14 19 55](https://cloud.githubusercontent.com/assets/985581/7105539/0c4d9926-e11f-11e4-9f2a-1d131e020549.png)

Works for me as described! Spotify is playing the selected song.

**Comment by bjarneo** [comment]
Awesome. Thanks :)
