### ISSUE TITLE
Ability to show "currently playing"

### ISSUE THREAD

**Issue by kennedyshead** [bjarneo/Spotipy#17]
Would be nice to like have this feature.

**Comment by bjarneo** [comment]
Good idea!

**Comment by bjarneo** [comment]
Note to self
DBUS
method call sender=:1.139 -> dest=:1.22 serial=24 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=Notify
   string "Spotify"
   uint32 0
   string ""
   string "Title here"
   string "Album here"

**Comment by bjarneo** [comment]
We do support this for linux at the moment. But it might be better if we add some kind of async code which updates the status bar when a new song is played.

**Comment by bjarneo** [comment]
Status bar is the ctrl+c/d line. 
![selection_159](https://cloud.githubusercontent.com/assets/1419214/21149344/7f5fdd3e-c15b-11e6-8922-2355add2fafb.png)
