### ISSUE TITLE
Not beeing able to change song

### ISSUE THREAD

**Issue by ckubrak** [bjarneo/Spotipy#24]
I have installed Pytify with pip on Arch Linux.
pityfy -x commands (n,p,pp,c) are working fine, but when I use the search function I can't change to the selected song.

**Comment by bjarneo** [comment]
Hi

Thanks for your feedback.

Which version of pytify is it? Newest?

**Comment by ckubrak** [comment]
I have installed it yesterday from pip, so I guess it's the newest. As soon as I get home I'll post the exact version

Edit: I don't know how to check the pytify version

**Comment by bjarneo** [comment]
@ckubrak Do you get the version if you start pytify? pytify 3.1.5 [https://github.com/bjarneo/Pytify]

Anyways. I'll check if I get the same error and try to solve it.

**Comment by bjarneo** [comment]
@ckubrak Is this still an issue?

**Comment by ckubrak** [comment]
@bjarneo not anymore!
