### ISSUE TITLE
Create  a setup.py and register in Pypi to install via PIP

### ISSUE THREAD

**Issue by arruda** [bjarneo/Spotipy#3]
It would be nice to install it using `pip install spotipy` or something like it.
Just have to take note that there is already a registered python package with the name spotipy: https://github.com/plamere/spotipy

**Comment by bjarneo** [comment]
I'll upload as fast as I can register an account. Seems to be some register issues. To bad spotipy is taken. Thanks for the advice.

**Comment by mazulo** [comment]
What do you think about `pip install spotipy-cli`? It's available.

**Comment by bjarneo** [comment]
pip install spotipy-cli sounds nice. I'll get it up and running soon.

**Comment by arruda** [comment]
\o/

**Comment by bjarneo** [comment]
pytify package is out
