### ISSUE TITLE
How about tests?

### ISSUE THREAD

**Issue by lk-geimfari** [bjarneo/Spotipy#33]
As the expense of having to add tests?

**Comment by bjarneo** [comment]
Tests are absolutely something that should be added. :+1: 

What testing framework do you recommend?

**Comment by lk-geimfari** [comment]
@bjarneo I think that the standard [unittests](https://docs.python.org/2/library/unittest.html) library is good choice, but and [py.test](http://doc.pytest.org/en/latest/) very good. Let me know which one you choose. I can help you write tests.

**Comment by bjarneo** [comment]
@lk-geimfari Let's use unittests. Mostly because I've never written a test in Python before, and want to get my hands dirty using the built in testing solution.

Help is appreciated :) 

I guess some code needs a refactor in order to test them more easily also.

**Comment by lk-geimfari** [comment]
@bjarneo I will try to write the basic tests today and send you PR.

**Comment by bjarneo** [comment]
@lk-geimfari awesome!

**Comment by lk-geimfari** [comment]
I want to write tests but i can't run project on Linux. I have some problems with dbus. Sorry.

**Comment by bjarneo** [comment]
@lk-geimfari No worries. Thanks for trying!
