### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by naveenkumarsangi** [bjarneo/Spotipy#37]
installed via pip just now
```
python v3.5.2
pip v9.0.1
python-dbus [installed]
OS => arch linux
kernel => 4.8.13
architecture => x86_64
```
Traceback [here](http://pastebin.com/65sMUbgG)

**Comment by lk-geimfari** [comment]
Also `dbus` that was be installed with `pip` does not import, but i think that is not a problem of `Pytify`.
