### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by calebmeyer** [bjarneo/Spotipy#4]
Looks like this library would be fairly easy to add python 3 support to. I get an error on line 49 of the cli.py file (where we print).

**Comment by bjarneo** [comment]
Should be a quick fix then

**Comment by bjarneo** [comment]
Could you check if it works with python3 now?

**Comment by bjarneo** [comment]
I believe there is more issues than print. I'll check when I get the time.

**Comment by bjarneo** [comment]
It now supports python3

**Comment by calebmeyer** [comment]
Thank you!
