### ISSUE TITLE
Some errors occured. Try restart or start Spotify. 

### ISSUE THREAD

**Issue by baif666** [bjarneo/Spotipy#40]
When I run pytify in CLI:
```

$ pytify

Some errors occured. Try restart or start Spotify. 

```
I install following the tutorial and I did it in Mint, python3.4.3
I don't know what happened, and I will try to fix it myself if there are more information.

**Comment by bjarneo** [comment]
Do you have spotify running in the background?

**Comment by bjarneo** [comment]
Try to print the exception at line 18 in this file: pytify/dbus/interface.py

**Comment by bjarneo** [comment]
The only reason you get this error message is if Spotify is not running on your computer. It checks if spotify exists at MediaPlayer2 in the dbus object, if not it throws an exception, and we quite the application with that message.

**Comment by baif666** [comment]
I saw it, so this message means I don't have Spotify running in the background. But how do I set up it?

**Comment by bjarneo** [comment]
That's correct. Then you just need to start Spotify. Pytify is just a cli application which controls Spotify.

https://www.spotify.com/no/download/linux/

**Comment by bjarneo** [comment]
@baif666 Did you manage to get it work?

**Comment by baif666** [comment]
@bjarneo Yeah, Pytify works well after I installed and started Spotify. Thanks. But I think you can improve your error message. For example, "Some errors occured. Try restart or start Spotify. Pytify is just a cli application which controls Spotify. So you can't use Pytify without Spotify." If I find a new issue, I'll report it.
Thanks for your contribution.
