### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by bjarneo** [bjarneo/Spotipy#41]
We need a logo! Up for grabs!

Must be clean. Simple.

**Comment by darnassiano** [comment]
![captura de pantalla de 2016-12-14 11-34-03](https://cloud.githubusercontent.com/assets/18491554/21193280/5df3063a-c1f1-11e6-921e-72fb7abff604.png)
How's about a command prompt ')))' ?

**Comment by YngveMolnes** [comment]
An idea - http://image.prntscr.com/image/f94f06c284724fba9b92fd94f8189788.png

**Comment by bjarneo** [comment]
@darnassiano Not sure if that's what I'm looking for. More in the direction @YngveMolnes created.

@YngveMolnes I like it! However, is it legal to use logo from python and spotify combined?

**Comment by YngveMolnes** [comment]
@bjarneo good point. I can draw up another one that does not infringe upon spotify.

**Comment by theodorosploumis** [comment]
Here are some proposals. They are not so "simple" but they are easy to understand (hope so!) No original logo of spotify is used but only its color palette. Waiting for your feedback! Thanks.

![proposals_v1](https://cloud.githubusercontent.com/assets/1315321/24324099/ba64faf4-1188-11e7-89be-c4f5269d8930.png)

**Comment by bjarneo** [comment]
Wow, I really like them. Especially the first one. I'll take a closer look later today!

**Comment by bjarneo** [comment]
@theodorosploumis I'm a bit slow to answer. Anyways, I really like the first one. Do you have it as an image with great resolution? :)

**Comment by theodorosploumis** [comment]
Sure. Svg and several png images. Enjoy!

[Logo_Pytify.zip](https://github.com/bjarneo/Pytify/files/900515/Logo_Pytify.zip)

**Comment by bjarneo** [comment]
Thank you! This is awesome!
