### ISSUE TITLE
17:18: syntax error: Expected end of line but found unknown token. (-2741)

### ISSUE THREAD

**Issue by niceperl** [bjarneo/Spotipy#6]
I got this error every time I type a number in order to play a song. Example:

``` text
What artist / song are you searching for?
> sinatra
#   | Artist                    | Song                           | Album                         
--- | ------------------------- | ------------------------------ | ------------------------------
1.  | Frank Sinatra             | Let It Snow! Let It Snow! Let  | Christmas Songs By Sinatra    
2.  | Frank Sinatra             | Santa Claus Is Comin' to Town  | Christmas Songs By Sinatra   
...
15. | Frank Sinatra             | Have Yourself a Merry Little C | Christmas Songs By Sinatra    
Last five search results:
sinatra

Type song number and press <enter> to play. Press <enter> for new search.
> 1
17:18: syntax error: Expected end of line but found unknown token. (-2741)

Playing: Frank Sinatra - Let It Snow! Let It Snow! Let
```

I am running cly.py on virtualenv, python 2.7.8 and Mac OS X Yosemite.
The song I selected didn't play

**Comment by bjarneo** [comment]
Seems to be some actionscript error. 

I need someone using OS X to look at the problem. 

http://stackoverflow.com/questions/2126291/bash-output-as-applescript-list-problems

**Comment by niceperl** [comment]
After this update, I got a new error:

22:32: syntax error: A identifier can’t go after this identifier. (-2740)

**Comment by bjarneo** [comment]
Same approach?

**Comment by niceperl** [comment]
Yes, but now the error message is different

**Comment by joined** [comment]
It works flawlessly for me, both with Python2 and Python3.
What OS X version are you using?
EDIT: Now I see, Yosemite. Really strange.

What happens if you type this in the Python REPL:

``` python
import subprocess
subprocess.call([
    'osascript',
    '-e',
    'tell app "Spotify" to play track "spotify:track:5amPczcUvAgcWR3iHQj2hu"'
])
```

?

**Comment by niceperl** [comment]
OS X Yosemite
10.10.1

**Comment by joined** [comment]
@niceperl See my updated question. Could you try executing that snippet?

**Comment by niceperl** [comment]
Sorry, it was my fault. I didn't have installed the spotify app. Perhaps this silly problem could help in the last term to improve the error messages...
Thanks!

**Comment by bjarneo** [comment]
@niceperl No worries. Perhaps we should do a 'is spotify installed' check. Have fun!
