### ISSUE TITLE
When attempting to execute "pytify", gives AttributeError

### ISSUE THREAD

**Issue by jklm264** [bjarneo/Spotipy#62]

**Comment by jklm264** [comment]
Has anyone else had this problem?

pytify 3.5.1 [https://github.com/bjarneo/Pytify]
Traceback (most recent call last):
  File "/usr/local/bin/pytify", line 11, in <module>
    load_entry_point('pytify==3.5.1', 'console_scripts', 'pytify')()
  File "build/bdist.macosx-10.12-x86_64/egg/pytify/cli.py", line 85, in main
  File "build/bdist.macosx-10.12-x86_64/egg/pytify/cli.py", line 19, in __init__
  File "build/bdist.macosx-10.12-x86_64/egg/pytify/cli.py", line 61, in run
  File "build/bdist.macosx-10.12-x86_64/egg/pytify/cli.py", line 72, in interaction
  File "build/bdist.macosx-10.12-x86_64/egg/pytify/prompt.py", line 56, in custom_prompt
  File "build/bdist.macosx-10.12-x86_64/egg/pytify/history.py", line 7, in history
AttributeError: type object 'Path' has no attribute 'home'

**Comment by bjarneo** [comment]
Haven't had this issue. Even tested on macos. Strange error. What python version do you use?

**Comment by fchovich** [comment]
happens on linux also, this is due to python version, but couldn't fix it yet. I'm using virtualenv, that may be the problem.

> (pytify) pytify|⇒ pytify 
> pytify 3.5.2 [https://github.com/bjarneo/Pytify]
> Traceback (most recent call last):
>   File "/usr/local/bin/pytify", line 11, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python2.7/dist-packages/pytify/cli.py", line 85, in main
>     App()
>   File "/usr/local/lib/python2.7/dist-packages/pytify/cli.py", line 19, in __init__
>     self.run()
>   File "/usr/local/lib/python2.7/dist-packages/pytify/cli.py", line 61, in run
>     self.interaction()
>   File "/usr/local/lib/python2.7/dist-packages/pytify/cli.py", line 72, in interaction
>     search_input = custom_prompt(self.pytify.get_current_playing())
>   File "/usr/local/lib/python2.7/dist-packages/pytify/prompt.py", line 56, in custom_prompt
>     history=history(),
>   File "/usr/local/lib/python2.7/dist-packages/pytify/history.py", line 7, in history
>     return FileHistory('%s/.pytify-search-history' % str(Path.home()))
> AttributeError: type object 'Path' has no attribute 'home'

**Comment by jklm264** [comment]
Using Python 3.7.1 with zsh, sry for the very late reply.

Update: This is interesting. It seems my system cannot find the prompt_toolkit module yet if I try to pip install it, it says it already exists in python2.7. (Fixed this issue)

Update2: When running with 2.7 it returns that Path AttributeError again.

Update3: The problem is coming from the pathlib module. I'm still investigating.
