### ISSUE TITLE
prompt-toolkit version requirement

### ISSUE THREAD

**Issue by iwconfig** [bjarneo/Spotipy#64]
I need to install prompt-toolkit>=1.0.15 but pytify requires prompt-toolkit==1.0.0.

Is version 1.0.0 necessary?

**Comment by bjarneo** [comment]
Could probably be updated :)

**Comment by goetzc** [comment]
It does work indeed with 1.0.15, `==` is not necessary. It does also work with spotipy 2.4.4.

**Comment by bjarneo** [comment]
https://github.com/bjarneo/Pytify/issues/68
