### ISSUE TITLE
Update to prompt toolkit 2

### ISSUE THREAD

**Issue by rien333** [bjarneo/Spotipy#68]
My package manager and pip only provide version 2 of the prompt-toolkit library. This version, among possibly other things, removed the `AbortAction` method, which causes pytify to fail. Other changes are listed in this [changelog](https://github.com/prompt-toolkit/python-prompt-toolkit/blob/2970d29936296349feb84aadb4217e1b9d57e2d3/docs/pages/upgrading/2.0.rst).

**Comment by bjarneo** [comment]
Hi, thanks for your feedback. Will look into this when I have some time. If anyone is interested in helping out, please do.

**Comment by bharath-123** [comment]
Hi, I am interested to work on this. I wish to work on this if this is still open?

**Comment by bjarneo** [comment]
Absolutely. Assigned you the issue.  :)

**Comment by bharath-123** [comment]
thanks!

**Comment by bjarneo** [comment]
https://github.com/bjarneo/Pytify/pull/70

**Comment by bjarneo** [comment]
This issue is solved. Thank you @bharath-123. Really appreciated. Newest version is 3.6.3 (I kind of screwed up the release a couple of times, haven't done it since 2017)

**Comment by rien333** [comment]
@bjarneo Can't see it in the releases tab yet. Btw, thanks for everyone's quick work!

**Comment by bjarneo** [comment]
I forgot. Released just now. @rien333 https://github.com/bjarneo/Pytify/releases/tag/v3.6.3
